// Copyright (c) Microsoft Corporation. All rights reserved. See License.txt in the project root for license information.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.Common.Configuration.FileBasedConfigurationSource.#Microsoft.Practices.EnterpriseLibrary.Common.Configuration.IConfigurationSourceTest.WatchedSections", Justification = "Test only interface")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.Common.Configuration.FileBasedConfigurationSource.#Microsoft.Practices.EnterpriseLibrary.Common.Configuration.IConfigurationSourceTest.ConfigSourceChanged(System.String)", Justification = "Test only interface")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.Common.Configuration.FileBasedConfigurationSource.#Microsoft.Practices.EnterpriseLibrary.Common.Configuration.IConfigurationSourceTest.ExternalConfigSourceChanged(System.String)", Justification = "Test only interface")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.Common.Configuration.FileBasedConfigurationSource.#Microsoft.Practices.EnterpriseLibrary.Common.Configuration.IConfigurationSourceTest.ConfigSourceWatcherMappings", Justification = "Test only interface")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.Common.Configuration.FileBasedConfigurationSource.#Microsoft.Practices.EnterpriseLibrary.Common.Configuration.IConfigurationSourceTest.WatchedConfigSources", Justification = "Test only interface")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.Common.Configuration.NamedElementCollection`1.#Microsoft.Practices.EnterpriseLibrary.Common.Configuration.IMergeableConfigurationElementCollection.ResetCollection(System.Collections.Generic.IEnumerable`1<System.Configuration.ConfigurationElement>)")]

