<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\..\..\package.props" />

	<PropertyGroup>
		<TargetFrameworks>net47;net10.0</TargetFrameworks>
		<!-- Support both .NET Framework 4.7 and .NET 8 -->
		<IsPackable>false</IsPackable>

		<AssemblyVersion>$(MajorVersion).0.0.0</AssemblyVersion>
		<FileVersion>$(Version).$(Revision)</FileVersion>

		<AssemblyName>$(PreAssemblyName).Common.TestSupport</AssemblyName>
		<RootNamespace>$(PreAssemblyName).Common.TestSupport</RootNamespace>
		<AssemblyTitle>Enterprise Library Shared Library Tests</AssemblyTitle>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net47'">
		<Reference Include="System.Configuration" />
		<Reference Include="System.Management" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
		<PackageReference Include="System.Configuration.ConfigurationManager" Version="7.0.0" />
		<PackageReference Include="System.Management" Version="7.0.0" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.5.0" />
		<PackageReference Include="MSTest.TestAdapter" Version="2.2.8" />
		<PackageReference Include="MSTest.TestFramework" Version="2.2.8" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\Common.licenseheader">
			<Link>Common.licenseheader</Link>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Src\Common\Common.csproj" />
	</ItemGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<DebugSymbols>true</DebugSymbols>
		<DebugType>full</DebugType>
		<Optimize>false</Optimize>
		<OutputPath>bin\Debug\</OutputPath>
		<DefineConstants>DEBUG;TRACE</DefineConstants>
		<ErrorReport>prompt</ErrorReport>
		<WarningLevel>4</WarningLevel>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
		<RunFxCop>false</RunFxCop>
		<FxCopRules>-Microsoft.Design#CA2210;-Microsoft.Reliability#CA2007</FxCopRules>
		<Prefer32Bit>false</Prefer32Bit>
		<CodeAnalysisRuleSet>..\Tests.ruleset</CodeAnalysisRuleSet>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<DebugSymbols>false</DebugSymbols>
		<Optimize>true</Optimize>
		<OutputPath>bin\Release\</OutputPath>
		<DefineConstants>TRACE</DefineConstants>
		<ErrorReport>prompt</ErrorReport>
		<WarningLevel>4</WarningLevel>
		<Prefer32Bit>false</Prefer32Bit>
		<CodeAnalysisRuleSet>..\Tests.ruleset</CodeAnalysisRuleSet>
	</PropertyGroup>
</Project>